matrix:
- name: Markdown
  expect_match: false
  apsell:
    mode: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - code
      - pre
  sources:
  - '*.md'
  - 'docs/**/*.md'
  - 'versioned_docs/**/*.md'
