name: Bug Report
description: Noticed any typos, misused terms, inconsistencies, or ambiguities in the docs? Let us know!
title: "Bug: "
labels: ["bug"]
assignees: [WanYixian, ShanlanLi]
body:
  - type: markdown
    attributes:
      value: |
        What an astute observer! Please describe the bug by filling out the form below. Thanks for making the docs better! 
  - type: input
    id: link
    attributes:
      label: Where's the bug?
      description: Where do you see the bug? A link to the doc page or the source file will do.
      placeholder: e.g. https://docs.risingwave.com/docs/current/intro/
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Describe the bug
      description: Tell us more about the bug you spotted. And if you have a revision suggestion in mind, we would love to hear it.
      value: "e.g. \n I noticed that there is a [typo/misused term/inconsistency/ambiguity] in [this sentence/paragraph/figure/section/screenshot]. \n [This] is incorrect because [...]. \n I think you folks should replace [this] with [that]. \n If you take a look at [this reference] you will agree with me. \n Cheers."
    validations:
      required: true
