name: Algolia Reindex
description: Algolia Reindex
inputs:
  CRAWLER_ID: 
    description: Crawler UUID
    required: true
  CRAWLER_USER_ID: 
    description: Crawler User Id
    required: true
  CRAWLER_API_KEY:
    description: Crawler API Key
    required: true
  ALGOLIA_APP_ID: 
    description: Algolia App Id
    required: true
  ALGOLIA_API_KEY: 
    description: Algolia API Key
    required: true
  CRAWLER_API_BASE_URL: 
    description: Crawler API Base URL
    required: true
# outputs:

runs:
  using: 'node16'
  main: 'index.js'
