name: Algolia Crawler
on:   
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  algolia_recrawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Algolia crawler recrawl (Push on Main branch)
        uses: algolia/algoliasearch-crawler-github-actions@v1
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          crawler-api-base-url: 'https://crawler.algolia.com/api/1/'
          site-url: 'https://risingwave.dev'
          crawler-name: risingwave
          override-config: true