name: Algolia Crawler
on:
  push:
    branches: [main]
    paths:
      - docusaurus.config.js
      - docs/**
      - sidebars.js
      - cloud/**
      - sidebarCloud.js
      - versioned_docs/**
      - versioned_sidebars/**

jobs:
  algolia_reindex:
    name: Algolia Reindex
    runs-on: ubuntu-latest
    steps:
      - name: Prepare basic auth token
        id: prepare
        run: |
          token=`echo "${{secrets.CRAWLER_USER_ID}}:${{secrets.CRAWLER_API_KEY}}" | base64`
          echo "token=$token" >> $GITHUB_OUTPUT
      - name: Trigger reindex
        id: trigger
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://crawler.algolia.com/api/1/crawlers/${{secrets.CRAWLER_ID}}/reindex"
          method: "POST"
          customHeaders: '{"Authorization": "Basic ${{steps.prepare.outputs.token}}", "Content-Type": "application/json"}'
      - name: Post triggering
        run: echo "Triggered reindex task ${{ fromJson(steps.trigger.outputs.response).taskId }}"
