name: Algolia Crawler
on:
  push:
    branches: [main]
    paths:
      - docusaurus.config.js
      - docs/**
      - sidebars.js
      - cloud/**
      - sidebarCloud.js
      - versioned_docs/**
      - versioned_sidebars/**

jobs:
  algolia_reindex:
    name: Algolia Reindex
    runs-on: ubuntu-latest
    steps:
      - name: Trigger reindex
        id: trigger
        run: |
          out=`curl -X POST -H "Content-Type: application/json" --user ${{secrets.CRAWLER_USER_ID}}:${{secrets.CRAWLER_API_KEY}} "https://crawler.algolia.com/api/1/crawlers/${{secrets.CRAWLER_ID}}/reindex"`
          echo "response=$out" >> $GITHUB_OUTPUT
      - name: Post triggering
        run: echo "Triggered reindex task ${{ fromJson(steps.trigger.outputs.response).taskId }}"
