name: spellcheck
on:
  pull_request:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: typos-action
        uses: crate-ci/typos@v1.23.6
        with:
          files: ./docs ./versioned_docs ./cloud ./README.md

      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@0.35.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
